// Generated by gencpp from file custom_msgs/CustomMessage.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CUSTOMMESSAGE_H
#define CUSTOM_MSGS_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct CustomMessage_
{
  typedef CustomMessage_<ContainerAllocator> Type;

  CustomMessage_()
    : temprature(0)
    , motor_stat(false)
    , debug_message()  {
    }
  CustomMessage_(const ContainerAllocator& _alloc)
    : temprature(0)
    , motor_stat(false)
    , debug_message(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _temprature_type;
  _temprature_type temprature;

   typedef uint8_t _motor_stat_type;
  _motor_stat_type motor_stat;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _debug_message_type;
  _debug_message_type debug_message;





  typedef boost::shared_ptr< ::custom_msgs::CustomMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::CustomMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessage_

typedef ::custom_msgs::CustomMessage_<std::allocator<void> > CustomMessage;

typedef boost::shared_ptr< ::custom_msgs::CustomMessage > CustomMessagePtr;
typedef boost::shared_ptr< ::custom_msgs::CustomMessage const> CustomMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::CustomMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::CustomMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::CustomMessage_<ContainerAllocator1> & lhs, const ::custom_msgs::CustomMessage_<ContainerAllocator2> & rhs)
{
  return lhs.temprature == rhs.temprature &&
    lhs.motor_stat == rhs.motor_stat &&
    lhs.debug_message == rhs.debug_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::CustomMessage_<ContainerAllocator1> & lhs, const ::custom_msgs::CustomMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f537432f8f1c04503d008c5851a94e1d";
  }

  static const char* value(const ::custom_msgs::CustomMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf537432f8f1c0450ULL;
  static const uint64_t static_value2 = 0x3d008c5851a94e1dULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/CustomMessage";
  }

  static const char* value(const ::custom_msgs::CustomMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 temprature\n"
"bool motor_stat\n"
"string debug_message\n"
;
  }

  static const char* value(const ::custom_msgs::CustomMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::CustomMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temprature);
      stream.next(m.motor_stat);
      stream.next(m.debug_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::CustomMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::CustomMessage_<ContainerAllocator>& v)
  {
    s << indent << "temprature: ";
    Printer<int64_t>::stream(s, indent + "  ", v.temprature);
    s << indent << "motor_stat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_stat);
    s << indent << "debug_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.debug_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CUSTOMMESSAGE_H
