// Generated by gencpp from file Robot_Messages/CircleAreaRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_CIRCLEAREAREQUEST_H
#define ROBOT_MESSAGES_MESSAGE_CIRCLEAREAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Robot_Messages
{
template <class ContainerAllocator>
struct CircleAreaRequest_
{
  typedef CircleAreaRequest_<ContainerAllocator> Type;

  CircleAreaRequest_()
    : radius(0.0)  {
    }
  CircleAreaRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)  {
  (void)_alloc;
    }



   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CircleAreaRequest_

typedef ::Robot_Messages::CircleAreaRequest_<std::allocator<void> > CircleAreaRequest;

typedef boost::shared_ptr< ::Robot_Messages::CircleAreaRequest > CircleAreaRequestPtr;
typedef boost::shared_ptr< ::Robot_Messages::CircleAreaRequest const> CircleAreaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator1> & lhs, const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator1> & lhs, const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Robot_Messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34d1b51a3aa2a07a0194bc3c5de27677";
  }

  static const char* value(const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34d1b51a3aa2a07aULL;
  static const uint64_t static_value2 = 0x0194bc3c5de27677ULL;
};

template<class ContainerAllocator>
struct DataType< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Robot_Messages/CircleAreaRequest";
  }

  static const char* value(const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 radius\n"
;
  }

  static const char* value(const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleAreaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Robot_Messages::CircleAreaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Robot_Messages::CircleAreaRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_CIRCLEAREAREQUEST_H
