// Generated by gencpp from file Robot_Messages/TestSrvResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_TESTSRVRESPONSE_H
#define ROBOT_MESSAGES_MESSAGE_TESTSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Robot_Messages
{
template <class ContainerAllocator>
struct TestSrvResponse_
{
  typedef TestSrvResponse_<ContainerAllocator> Type;

  TestSrvResponse_()
    : success(false)  {
    }
  TestSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TestSrvResponse_

typedef ::Robot_Messages::TestSrvResponse_<std::allocator<void> > TestSrvResponse;

typedef boost::shared_ptr< ::Robot_Messages::TestSrvResponse > TestSrvResponsePtr;
typedef boost::shared_ptr< ::Robot_Messages::TestSrvResponse const> TestSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Robot_Messages::TestSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Robot_Messages::TestSrvResponse_<ContainerAllocator1> & lhs, const ::Robot_Messages::TestSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Robot_Messages::TestSrvResponse_<ContainerAllocator1> & lhs, const ::Robot_Messages::TestSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Robot_Messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::Robot_Messages::TestSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Robot_Messages/TestSrvResponse";
  }

  static const char* value(const ::Robot_Messages::TestSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success                \n"
"  \n"
"\n"
;
  }

  static const char* value(const ::Robot_Messages::TestSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Robot_Messages::TestSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Robot_Messages::TestSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_TESTSRVRESPONSE_H
