// Generated by gencpp from file Robot_Messages/CircleAreaResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_CIRCLEAREARESPONSE_H
#define ROBOT_MESSAGES_MESSAGE_CIRCLEAREARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Robot_Messages
{
template <class ContainerAllocator>
struct CircleAreaResponse_
{
  typedef CircleAreaResponse_<ContainerAllocator> Type;

  CircleAreaResponse_()
    : area(0.0)  {
    }
  CircleAreaResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef double _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CircleAreaResponse_

typedef ::Robot_Messages::CircleAreaResponse_<std::allocator<void> > CircleAreaResponse;

typedef boost::shared_ptr< ::Robot_Messages::CircleAreaResponse > CircleAreaResponsePtr;
typedef boost::shared_ptr< ::Robot_Messages::CircleAreaResponse const> CircleAreaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator1> & lhs, const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator1> & lhs, const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Robot_Messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "502b7bd5115b3b4f57d03446f9208d12";
  }

  static const char* value(const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x502b7bd5115b3b4fULL;
  static const uint64_t static_value2 = 0x57d03446f9208d12ULL;
};

template<class ContainerAllocator>
struct DataType< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Robot_Messages/CircleAreaResponse";
  }

  static const char* value(const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 area\n"
"\n"
;
  }

  static const char* value(const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleAreaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Robot_Messages::CircleAreaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Robot_Messages::CircleAreaResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_CIRCLEAREARESPONSE_H
