// Generated by gencpp from file Robot_Messages/TestSrv.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_TESTSRV_H
#define ROBOT_MESSAGES_MESSAGE_TESTSRV_H

#include <ros/service_traits.h>


#include <Robot_Messages/TestSrvRequest.h>
#include <Robot_Messages/TestSrvResponse.h>


namespace Robot_Messages
{

struct TestSrv
{

typedef TestSrvRequest Request;
typedef TestSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TestSrv
} // namespace Robot_Messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Robot_Messages::TestSrv > {
  static const char* value()
  {
    return "43bbf4bb5cd2c8d90af552c736d2ab6d";
  }

  static const char* value(const ::Robot_Messages::TestSrv&) { return value(); }
};

template<>
struct DataType< ::Robot_Messages::TestSrv > {
  static const char* value()
  {
    return "Robot_Messages/TestSrv";
  }

  static const char* value(const ::Robot_Messages::TestSrv&) { return value(); }
};


// service_traits::MD5Sum< ::Robot_Messages::TestSrvRequest> should match
// service_traits::MD5Sum< ::Robot_Messages::TestSrv >
template<>
struct MD5Sum< ::Robot_Messages::TestSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Robot_Messages::TestSrv >::value();
  }
  static const char* value(const ::Robot_Messages::TestSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Robot_Messages::TestSrvRequest> should match
// service_traits::DataType< ::Robot_Messages::TestSrv >
template<>
struct DataType< ::Robot_Messages::TestSrvRequest>
{
  static const char* value()
  {
    return DataType< ::Robot_Messages::TestSrv >::value();
  }
  static const char* value(const ::Robot_Messages::TestSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Robot_Messages::TestSrvResponse> should match
// service_traits::MD5Sum< ::Robot_Messages::TestSrv >
template<>
struct MD5Sum< ::Robot_Messages::TestSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Robot_Messages::TestSrv >::value();
  }
  static const char* value(const ::Robot_Messages::TestSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Robot_Messages::TestSrvResponse> should match
// service_traits::DataType< ::Robot_Messages::TestSrv >
template<>
struct DataType< ::Robot_Messages::TestSrvResponse>
{
  static const char* value()
  {
    return DataType< ::Robot_Messages::TestSrv >::value();
  }
  static const char* value(const ::Robot_Messages::TestSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_TESTSRV_H
