// Generated by gencpp from file Robot_Messages/BatterySrvRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_BATTERYSRVREQUEST_H
#define ROBOT_MESSAGES_MESSAGE_BATTERYSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Robot_Messages
{
template <class ContainerAllocator>
struct BatterySrvRequest_
{
  typedef BatterySrvRequest_<ContainerAllocator> Type;

  BatterySrvRequest_()
    : Percentage(0)  {
    }
  BatterySrvRequest_(const ContainerAllocator& _alloc)
    : Percentage(0)  {
  (void)_alloc;
    }



   typedef int32_t _Percentage_type;
  _Percentage_type Percentage;





  typedef boost::shared_ptr< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BatterySrvRequest_

typedef ::Robot_Messages::BatterySrvRequest_<std::allocator<void> > BatterySrvRequest;

typedef boost::shared_ptr< ::Robot_Messages::BatterySrvRequest > BatterySrvRequestPtr;
typedef boost::shared_ptr< ::Robot_Messages::BatterySrvRequest const> BatterySrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator1> & lhs, const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Percentage == rhs.Percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator1> & lhs, const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Robot_Messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ee1b68ceeb45a995ccefcb6bba2eb80";
  }

  static const char* value(const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ee1b68ceeb45a99ULL;
  static const uint64_t static_value2 = 0x5ccefcb6bba2eb80ULL;
};

template<class ContainerAllocator>
struct DataType< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Robot_Messages/BatterySrvRequest";
  }

  static const char* value(const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Percentage\n"
;
  }

  static const char* value(const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatterySrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Robot_Messages::BatterySrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Robot_Messages::BatterySrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "Percentage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_BATTERYSRVREQUEST_H
