// Generated by gencpp from file Robot_Messages/BatterySrvResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_BATTERYSRVRESPONSE_H
#define ROBOT_MESSAGES_MESSAGE_BATTERYSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Robot_Messages
{
template <class ContainerAllocator>
struct BatterySrvResponse_
{
  typedef BatterySrvResponse_<ContainerAllocator> Type;

  BatterySrvResponse_()
    : Return(false)  {
    }
  BatterySrvResponse_(const ContainerAllocator& _alloc)
    : Return(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Return_type;
  _Return_type Return;





  typedef boost::shared_ptr< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BatterySrvResponse_

typedef ::Robot_Messages::BatterySrvResponse_<std::allocator<void> > BatterySrvResponse;

typedef boost::shared_ptr< ::Robot_Messages::BatterySrvResponse > BatterySrvResponsePtr;
typedef boost::shared_ptr< ::Robot_Messages::BatterySrvResponse const> BatterySrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator1> & lhs, const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Return == rhs.Return;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator1> & lhs, const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Robot_Messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bf52b8741587164778bc66a525a7b48";
  }

  static const char* value(const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bf52b8741587164ULL;
  static const uint64_t static_value2 = 0x778bc66a525a7b48ULL;
};

template<class ContainerAllocator>
struct DataType< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Robot_Messages/BatterySrvResponse";
  }

  static const char* value(const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Return\n"
"\n"
;
  }

  static const char* value(const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Return);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatterySrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Robot_Messages::BatterySrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Robot_Messages::BatterySrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "Return: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Return);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_BATTERYSRVRESPONSE_H
